### ISSUE TITLE
Edit the href tag on the Return Home Button

### ISSUE THREAD

**Issue by dwaipayan05** [dwaipayan05/sme-nitk-website#2]
The href tag on Return Home Button for the **Convention20.html** has the wrong html name referenced. Change it to home.html along with the correct location

**Comment by 96RadhikaJadhav** [comment]
@dwaipayan05  Can I work on the issue?

**Comment by dwaipayan05** [comment]
> @dwaipayan05 Can I work on the issue?

Yes, Go Ahead
